---
- name: Include OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Import initialization tasks
  import_tasks: init.yml
  tags: ['always']

- name: Import install tasks
  import_tasks: install.yml
  tags: ['kerberos-client', 'kerberos-client-install']

- name: Import configuration tasks
  import_tasks: configure.yml
  tags: ['kerberos-client', 'kerberos-client-configure']

- name: Import deploy tasks
  import_tasks: deploy.yml
  when: kerberos_client__deploy | bool
...
